# Menggunakan image Python 3.12 sebagai base image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Menyalin file requirements.txt dan menginstal dependensi
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Menyalin seluruh kode aplikasi ke dalam container
COPY . .

# Mengatur variabel lingkungan
ENV FLASK_APP=run.py
ENV FLASK_ENV=production

# Menjalankan aplikasi
CMD ["python", "run.py"]